spring:
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    host: 192.168.80.128
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system_design
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
server:
  port: 9090
aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-hongkong.aliyuncs.com

    accessKeyId: LTAI5tDm8yJFqB4bRMwP7nUR
    # 访问身份验证中用到用户标识
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: KCxJLisKVdIRjdhYHXk7Jlzv6Qp2Ke
    # oss的存储空间
    bucketName: zzzk1-mall-project
    # 上传文件大小(M)
    maxSize: 3
    # 上传文件夹路径前缀
    dir:
      prefix: images/
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /msg # rabbitmq的虚拟host
    username: root # rabbitmq的用户名
    password: root # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
